### ISSUE TITLE
关于文中实验的准确率。

### ISSUE THREAD

**Issue by zimuyuan** [kaiwang960112/Self-Cure-Network#10]
作者你好，很高兴看了你的文章，关于文中实验的准确率是用原始标签来计算还是用 relabeling 模块修正后的标签计算的?

**Comment by kaiwang960112** [comment]
relabeling是针对训练数据的策略，最后评测的数据标签是原始标签。谢谢关注哈

**Comment by zimuyuan** [comment]
作者你好，我看到SCN的表7(c)中 FERPlus的准确率在ResNet18是88.01，不过还有一个IR50网的准确率是89.35，IR50表示的是和RsetNet18一样为特征提出网络吗，IR50给的参考文献是 Additive angular margin loss for deep face recognition，这篇文章我没有细看，不过好像是说人脸识别的LOSS吧，好像看到介绍IR50网络啊。
