### ISSUE TITLE
源代码求助

### ISSUE THREAD

**Issue by wangye8899** [kaiwang960112/Self-Cure-Network#11]
师兄（师姐）你好，我是吉林大学计算机学院的研一学生，目前在做人脸表情分析的相关研究。看了您的论文，感觉真的棒，真的应该向您学习。最近想附先您的实验，所以需要您的源代码。如果您方便是否可以发给我呢？
邮箱：3091485316@qq.com
微信:：wangye889905

**Comment by kaiwang960112** [comment]
你可以加我微信，kaiwang-siat-2017，最近在答辩，可能回复不够及时。-------- 原始邮件 --------发件人： wangye8899 <notifications@github.com>日期： 2020年5月18日周一 上午9:50收件人： kaiwang960112/Self-Cure-Network <Self-Cure-Network@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [kaiwang960112/Self-Cure-Network] 源代码求助 (#11)
师兄（师姐）你好，我是吉林大学计算机学院的研一学生，目前在做人脸表情分析的相关研究。看了您的论文，感觉真的棒，真的应该向您学习。最近想附先您的实验，所以需要您的源代码。如果您方便是否可以发给我呢？
邮箱：3091485316@qq.com
微信:：wangye889905

**Comment by lixingran666** [comment]
> 师兄（师姐）你好，我是吉林大学计算机学院的研一学生，目前在做人脸表情分析的相关研究。看了您的论文，感觉真的棒，真的应该向您学习。最近想附先您的实验，所以需要您的源代码。如果您方便是否可以发给我呢？
> 邮箱：[3091485316@qq.com](mailto:3091485316@qq.com)
> 微信:：wangye889905

同学你好，我也是研一刚好也做人脸表情分析，你收到源码了吗？可以分享一下吗？我们以后可以多多交流 。邮箱：1271025494@qq.com

**Comment by 17802592576** [comment]
-

> 师兄（师姐）你好，我是吉林大学计算机学院的研一学生，目前在做人脸表情分析的相关研究。看了您的论文，感觉真的棒，真的应该向您学习。最近想附先您的实验，所以需要您的源代码。如果您方便是否可以发给我呢？
> 邮箱：[3091485316@qq.com](mailto:3091485316@qq.com)
> 微信:：wangye889905

同求源码呀同学，有源码可以交流下不，不胜感激。
邮箱：1121612687@qq.com

**Comment by kaiwang960112** [comment]
代码已经开源
