### ISSUE TITLE
对于每个batch，relabel和计算loss的先后顺序问题

### ISSUE THREAD

**Issue by 809052835** [kaiwang960112/Self-Cure-Network#12]
请问对于每个batch的relabel过程，是计算loss之后再relabel，还是relabel之后再计算loss呢？

**Comment by kaiwang960112** [comment]
这个问题问的很好，我论文里面是先保存label。本轮仍旧使用老标签。关于本轮就使用的实验近期也会放出来。最近一直在搞毕业事宜。谢谢大家的等待

**Comment by kaiwang960112** [comment]
本轮就是用新标签
