### ISSUE TITLE
对于未使用大规模人脸数据集预训练的测试方式，baseline和scn跑出的结果没有什么差异

### ISSUE THREAD

**Issue by skywangch** [kaiwang960112/Self-Cure-Network#14]
在你们给出的代码的基础上，我去掉了了scn里面的方法，改回baseline进行训练，发现baseline的表现和scn基本差不多。你们也可以验证一下。

**Comment by kaiwang960112** [comment]
好的 我们试试 多谢

**Comment by kaiwang960112** [comment]
我今天放出了加了20%噪声的代码和txt，你们可以试下效果。我们这边用在imagenet数据集上预训练的模型，scn比baseline好很多。scn在rafdb数据集上可以达到82%的效果。

**Comment by PainLiu** [comment]
> 在你们给出的代码的基础上，我去掉了了scn里面的方法，改回baseline进行训练，发现baseline的表现和scn基本差不多。你们也可以验证一下。
请问你们用baseline在数据库上分别达到了多少识别率呢

**Comment by PainLiu** [comment]
> 在你们给出的代码的基础上，我去掉了了scn里面的方法，改回baseline进行训练，发现baseline的表现和scn基本差不多。你们也可以验证一下。
请问你们用baseline在数据库上分别达到了多少识别率呢

**Comment by twinsyssy1018** [comment]
@skywangch 可以分享下 参数设置么 我不管怎么训 都只有70%左右，而且relabel一设置就过拟合了
