### ISSUE TITLE
WCE-Loss问题

### ISSUE THREAD

**Issue by lao-ling-jie** [kaiwang960112/Self-Cure-Network#17]
您好，感谢您出色的工作，最近在复现您的实验。在self-attention模块paper里说采用了WCE-Loss，为什么我在代码中看到的是CrossEntropyLoss交叉熵函数。

**Comment by kaiwang960112** [comment]
wce loss是在最后分类的prediction上再去乘一个权重，再去做ce发自我的华为手机

**Comment by lao-ling-jie** [comment]
> wce loss是在最后分类的prediction上再去乘一个权重，再去做ce发自我的华为手机
感谢您的解惑

**Comment by sunmusik** [comment]
> > wce loss是在最后分类的prediction上再去乘一个权重，再去做ce发自我的华为手机
> > 感谢您的解惑

请问代码里所说的这个乘以权重在哪儿，没看到啊
