### ISSUE TITLE
复现AffectNet上的实验结果

### ISSUE THREAD

**Issue by SJHNJU** [kaiwang960112/Self-Cure-Network#20]
您好！

我尝试在AffectNet上复现实验结果但是失败了，bs=1024，加载了ImageNet上的预训练模型，其他参数和论文中的一样。请问大佬在实验时在AffectNet上做人脸对齐了吗？请问能够发一份AffectNet上的实验代码，邮箱151180108@smail.nju.edu.cn，万分感谢！

**Comment by kaiwang960112** [comment]
你可能没有做样本平衡吧，我用了对齐。你记得去用下imbalanced sample

**Comment by SJHNJU** [comment]
感谢！我也做了对齐和样本平衡，请问：
1、论文里使用的样本平衡代码是RAN这个repo里的嘛？地址：https://github.com/kaiwang960112/Challenge-condition-FER-dataset/tree/master/AffectNet_dir/unbalanced_sample_train
2、然后预训练模型用的是imagenet上的还是ijba_res18_naive.pth.tar呀

> 你可能没有做样本平衡吧，我用了对齐。你记得去用下imbalanced sample

**Comment by kaiwang960112** [comment]
对的  我用的是ijba这个

**Comment by SJHNJU** [comment]
嗯呢谢谢大佬！改变了数据采样方式后明显提升了，非常感谢

**Comment by SJHNJU** [comment]
8/19更新：感谢大佬，改变数据采样方式和预训练模型后，成功复现出affectnet上的结果，bs=64，结果60.23

**Comment by kaiwang960112** [comment]
好滴好滴，不客气。

**Comment by kuanxin** [comment]
> 8/19更新：感谢大佬，改变数据采样方式和预训练模型后，成功复现出affectnet上的结果，bs=64，结果60.23

我目前照您的方式，testing都还是递减的状况...
请问能否发一份AffectNet上实验成功的代码吗，感谢
email: c05303330@gmail.com

**Comment by hopelyj** [comment]
> 8/19更新：感谢大佬，改变数据采样方式和预训练模型后，成功复现出affectnet上的结果，bs=64，结果60.23

您好，按照文章一直没有再AffectNet上实验成功，能够发一份在AffectNet上的代码。感谢
yongjie.li@pku.edu.cn

**Comment by kaiwang960112** [comment]
yongjie，你可以把code发我邮箱，kai.wang960112@gmail.com，我最近在赶aaai，可能回复不会太及时

**Comment by wangwangbuaa** [comment]
> 8/19更新：感谢大佬，改变数据采样方式和预训练模型后，成功复现出affectnet上的结果，bs=64，结果60.23

您好，按照文章一直没有再AffectNet上实验成功，能否发一份在AffectNet上成功复现的代码。感谢
sy1703711@buaa.edu.cn

**Comment by SJHNJU** [comment]
> > 8/19更新：感谢大佬，改变数据采样方式和预训练模型后，成功复现出affectnet上的结果，bs=64，结果60.23
> 
> 您好，按照文章一直没有再AffectNet上实验成功，能否发一份在AffectNet上成功复现的代码。感谢
> [sy1703711@buaa.edu.cn](mailto:sy1703711@buaa.edu.

**Comment by onwaiers** [comment]
> 8/19更新：感谢大佬，改变数据采样方式和预训练模型后，成功复现出affectnet上的结果，bs=64，结果60.23

你好，我现在使用了人脸对齐、ijba的预训练模型和，但训练时仍会出现训练精度不断上升，测试精度先上升后下降，加入了drop_rate和强数据增广，学习率调为0.0001，仍会出现测试精度先上升后下降的现象，请问你在训练AffectNet时，在rafdb代码上还做了什么修改吗？
