### ISSUE TITLE
FERPlus标签问题

### ISSUE THREAD

**Issue by wly93** [kaiwang960112/Self-Cure-Network#21]
我读了您的这篇论文。有一个问题，FERPlus数据集有一些图片的标签打分存在多个最大值，对于这种情况您是如何处理的

**Comment by yuebaitianqing** [comment]
> 我读了您的这篇论文。有一个问题，FERPlus数据集有一些图片的标签打分存在多个最大值，对于这种情况您是如何处理的

您好，有解决的方法吗，我也是被这个困扰
