### ISSUE TITLE
请问可以分享与训练模型吗

### ISSUE THREAD

**Issue by lycwgf** [kaiwang960112/Self-Cure-Network#22]
您还，可以分享一个预训练模型的链接吗？多谢，

**Comment by kaiwang960112** [comment]
我的另外一篇开源文章，RAN，下拉到最后，下载一波，加油哈发自我的华为手机-------- 原始邮件 --------发件人： lycwgf <notifications@github.com>日期： 2020年8月24日周一 傍晚5:07收件人： kaiwang960112/Self-Cure-Network <Self-Cure-Network@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [kaiwang960112/Self-Cure-Network] 请问可以分享与训练模型吗 (#22)

您还，可以分享一个预训练模型的链接吗？多谢，

**Comment by lycwgf** [comment]
您好，我用RAF训练，在RAF上测试，resnet+pretrain能够达到87%，用Affectnet 训练， RAF测试，resnet+without pretrain和resnet+pretrain的情况下都只能达到77%，我想请教一下这个是正常的吗？还是我训练的有问题？

**Comment by kaiwang960112** [comment]
我没试过affectnet训然后rafdb测哈，跨数据集提升性能确实是一个啃的骨头

**Comment by bohelion** [comment]
> 您好，我用RAF训练，在RAF上测试，resnet+pretrain能够达到87%，用Affectnet 训练， RAF测试，resnet+without pretrain和resnet+pretrain的情况下都只能达到77%，我想请教一下这个是正常的吗？还是我训练的有问题？

您好，可以把您训练的代码给我发一份吗？想借鉴一下，非常感谢！353099145@qq.com
