### ISSUE TITLE
您好，请问可以分享SCN的预训练模型吗？(*^▽^*)

### ISSUE THREAD

**Issue by zmxhhh** [kaiwang960112/Self-Cure-Network#24]

**Comment by kaiwang960112** [comment]
赶完aaai后我看看哈 你给我kai.wang960112@gmail.com邮箱里留言下

**Comment by zmxhhh** [comment]
非常感谢，之前因为一些原因没有复现出来，所以才向您请求预训练模型。之后问题解决已经复现出来了。非常感谢您！

**Comment by jinbaoziyl** [comment]
> 非常感谢，之前因为一些原因没有复现出来，所以才向您请求预训练模型。之后问题解决已经复现出来了。非常感谢您！

方便发一份预训练模型吗？ 我真的非常需要  邮箱185284033@qq.com

**Comment by FuGang-cmd** [comment]
可以发一份预训练模型吗？邮箱13031712361@163.com，不胜感谢

**Comment by qy58amy** [comment]
> 非常感谢，之前因为一些原因没有复现出来，所以才向您请求预训练模型。之后问题解决已经复现出来了。非常感谢您！

您好，方便发一下预训练模型吗？谢谢！1548360044@qq.com

**Comment by jinbaoziyl** [comment]
这个是其中一个同学共享给我的， 请你查看，&nbsp; 谢谢各位的分享！！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kaiwang960112/Self-Cure-Network"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月27日(星期二) 中午11:16
收件人:&nbsp;"kaiwang960112/Self-Cure-Network"<Self-Cure-Network@noreply.github.com&gt;;
抄送:&nbsp;"杨林"<185284033@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [kaiwang960112/Self-Cure-Network] 您好，请问可以分享SCN的预训练模型吗？(*^▽^*) (#24)





  
非常感谢，之前因为一些原因没有复现出来，所以才向您请求预训练模型。之后问题解决已经复现出来了。非常感谢您！
  
您好，方便发一下预训练模型吗？谢谢！1548360044@qq.com
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

epoch70_acc0.8719.pth (128.03M, 2020年11月27日 21:59 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7d363834fce09c93f603333f4265514b02575a06505156061a570901064857540e07150c5c53524900575c0454045355005009016470630147595b5c53553c055455081a5c52525d19464c5c6458&code=7684decd

**Comment by QingyangZhang** [comment]
> 这个是其中一个同学共享给我的， 请你查看，&nbsp; 谢谢各位的分享！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kaiwang960112/Self-Cure-Network" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月27日(星期二) 中午11:16 收件人:&nbsp;"kaiwang960112/Self-Cure-Network"<Self-Cure-Network@noreply.github.com&gt;; 抄送:&nbsp;"杨林"<185284033@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [kaiwang960112/Self-Cure-Network] 您好，请问可以分享SCN的预训练模型吗？(*^▽^*) (#24) 非常感谢，之前因为一些原因没有复现出来，所以才向您请求预训练模型。之后问题解决已经复现出来了。非常感谢您！ 您好，方便发一下预训练模型吗？谢谢！1548360044@qq.com — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 从QQ邮箱发来的超大附件 epoch70_acc0.8719.pth (128.03M, 2020年11月27日 21:59 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7d363834fce09c93f603333f4265514b02575a06505156061a570901064857540e07150c5c53524900575c0454045355005009016470630147595b5c53553c055455081a5c52525d19464c5c6458&code=7684decd



> 这个是其中一个同学共享给我的， 请你查看，&nbsp; 谢谢各位的分享！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kaiwang960112/Self-Cure-Network" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月27日(星期二) 中午11:16 收件人:&nbsp;"kaiwang960112/Self-Cure-Network"<Self-Cure-Network@noreply.github.com&gt;; 抄送:&nbsp;"杨林"<185284033@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [kaiwang960112/Self-Cure-Network] 您好，请问可以分享SCN的预训练模型吗？(*^▽^*) (#24) 非常感谢，之前因为一些原因没有复现出来，所以才向您请求预训练模型。之后问题解决已经复现出来了。非常感谢您！ 您好，方便发一下预训练模型吗？谢谢！1548360044@qq.com — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 从QQ邮箱发来的超大附件 epoch70_acc0.8719.pth (128.03M, 2020年11月27日 21:59 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7d363834fce09c93f603333f4265514b02575a06505156061a570901064857540e07150c5c53524900575c0454045355005009016470630147595b5c53553c055455081a5c52525d19464c5c6458&code=7684decd

您好，链接过期了，方便发我一份预训练模型吗？非常感谢您！740869014@qq.com

**Comment by yuhaoha** [comment]
> 这个是其中一个同学共享给我的， 请你查看，&nbsp; 谢谢各位的分享！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kaiwang960112/Self-Cure-Network" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月27日(星期二) 中午11:16 收件人:&nbsp;"kaiwang960112/Self-Cure-Network"<Self-Cure-Network@noreply.github.com&gt;; 抄送:&nbsp;"杨林"<185284033@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [kaiwang960112/Self-Cure-Network] 您好，请问可以分享SCN的预训练模型吗？(*^▽^*) (#24) 非常感谢，之前因为一些原因没有复现出来，所以才向您请求预训练模型。之后问题解决已经复现出来了。非常感谢您！ 您好，方便发一下预训练模型吗？谢谢！1548360044@qq.com — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 从QQ邮箱发来的超大附件 epoch70_acc0.8719.pth (128.03M, 2020年11月27日 21:59 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7d363834fce09c93f603333f4265514b02575a06505156061a570901064857540e07150c5c53524900575c0454045355005009016470630147595b5c53553c055455081a5c52525d19464c5c6458&code=7684decd

您好，链接过期了，方便发我一份预训练模型吗？万分感谢您！<1660754769@qq.com>

**Comment by twinsyssy1018** [comment]
@jinbaoziyl 你好 链接过期了 方便再共享一下么？

**Comment by kaiwang960112** [comment]
已经在scn的主页底部共享了预训练模型，欢迎下载

twinsyssy1018 ***@***.***> 於 2021年4月2日週五 下午4:14寫道：

**Comment by lujiazhou** [comment]
> 这个是其中一个同学共享给我的， 请你查看，&nbsp; 谢谢各位的分享！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kaiwang960112/Self-Cure-Network" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月27日(星期二) 中午11:16 收件人:&nbsp;"kaiwang960112/Self-Cure-Network"<Self-Cure-Network@noreply.github.com&gt;; 抄送:&nbsp;"杨林"<185284033@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [kaiwang960112/Self-Cure-Network] 您好，请问可以分享SCN的预训练模型吗？(*^▽^*) (#24) 非常感谢，之前因为一些原因没有复现出来，所以才向您请求预训练模型。之后问题解决已经复现出来了。非常感谢您！ 您好，方便发一下预训练模型吗？谢谢！1548360044@qq.com — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 从QQ邮箱发来的超大附件 epoch70_acc0.8719.pth (128.03M, 2020年11月27日 21:59 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7d363834fce09c93f603333f4265514b02575a06505156061a570901064857540e07150c5c53524900575c0454045355005009016470630147595b5c53553c055455081a5c52525d19464c5c6458&code=7684decd

您好，您的链接过期了，方便重新分享一下吗，万分感谢

**Comment by kaiwang960112** [comment]
https://drive.google.com/drive/folders/1dpDntw-2jLCNgjZ20W9aLg8a6DEEo7gX

你确定这个link不能用？

lujiazhou ***@***.***> 於 2021年4月9日週五 上午9:38寫道：

**Comment by BettyMei** [comment]
您好，底部的链接打不开，方便发一份SCN的预训练模型吗？谢谢 1005094519@qq.com

**Comment by Huang-feifei** [comment]
方便发一份预训练模型吗？1583286019@qq.com 谢谢！

**Comment by kaiwang960112** [comment]
在我的另外一个repo（RAN，Challenge-Fer-dataset）的最下面那个link里面下载。

fakerslo ***@***.***>于2022年3月25日 周五上午10:24写道：
