### ISSUE TITLE
License

### ISSUE THREAD

**Issue by javadziaratnia** [kaiwang960112/Self-Cure-Network#25]
Hi
Would you please clarify more about the license? Is it under the MIT license?

@kaiwang960112
@bruceche11 
@nzhq

**Comment by bruceche11** [comment]
@javadziaratnia  I am ok with everything you do with the code as my code is open entirely. But the net is belong to kaiwang960112 and nzhq so it would be better to get permission from them.

**Comment by javadziaratnia** [comment]
> @javadziaratnia I am ok with everything you do with the code as my code is open entirely. But the net is belong to kaiwang960112 and nzhq so it would be better to get permission from them.

Thank you very much for your reply.

I already mentioned @kaiwang960112 and @nzhq. Looking forward to get reply from them.

Best Regards,
Javad

**Comment by kaiwang960112** [comment]
hello, you can use this code for the academy purpose. If you use this code for other things, let me know. My email is kai.wang960112@gmail.com.  Thank you for your interest.
