### ISSUE TITLE
針對𝛼i的請教

### ISSUE THREAD

**Issue by hsiehchungting** [kaiwang960112/Self-Cure-Network#27]
您好~
閱讀過paper後，我想知道𝛼i是如何得出的?而𝛼i代表的是一張圖對7種表情的概率?還是說只針對最高的那種概率的分數?或者是它SelfAttention ImportanceWeighting 這個模塊就只是分辨它是否不確定的分數?

**Comment by kaiwang960112** [comment]
alpha是每个样本的importance回归值

**Comment by hsiehchungting** [comment]
感謝大神您的回答~
所以在dataset裡面有標記uncertain的值嗎?model才會去學習分辨uncertain的alpha?

**Comment by hsiehchungting** [comment]
我想了解importance 如何定義? 謝謝~

**Comment by kaiwang960112** [comment]
不需要标记，自我感知哪些是uncertainty，举个例子，你教小孩看了100张苹果的图片，下一次，你给他看一张椅子或者一张特别糊的照片，你告诉他是苹果，你觉得她会有几成把握相信这是苹果哈哈哈。

**Comment by hsiehchungting** [comment]
那model為什麼會預測uncertainty?是在paper中提到的pertaining weight 中有去訓練uncertaining嗎?如果沒有model怎麼會去判斷uncertain的程度。
謝謝您的回答。

**Comment by UEFI-code** [comment]
> 那model為什麼會預測uncertainty?是在paper中提到的pertaining weight 中有去訓練uncertaining嗎?如果沒有model怎麼會去判斷uncertain的程度。
> 謝謝您的回答。

你看一下代码train.py第250行， if i >= args.relabel_epoch，这似乎是假定每训练10个epoch网络就有一定的识别能力了

**Comment by UEFI-code** [comment]
> 不需要标记，自我感知哪些是uncertainty，举个例子，你教小孩看了100张苹果的图片，下一次，你给他看一张椅子或者一张特别糊的照片，你告诉他是苹果，你觉得她会有几成把握相信这是苹果哈哈哈。

准确来说，这个SCN的类比应该是，先给小孩看了100张苹果占大多数的图片，下一次再给他看一张椅子或者一张特别糊的照片，你告诉他是苹果，他觉得不对劲了再自己纠正过来😂

但是你先给他看的那100张图片，假如其中苹果有50张，另50张是其他各种东西的，而且还是乱序给他看的，效果是不是就emm

**Comment by hsiehchungting** [comment]
> > 不需要标记，自我感知哪些是uncertainty，举个例子，你教小孩看了100张苹果的图片，下一次，你给他看一张椅子或者一张特别糊的照片，你告诉他是苹果，你觉得她会有几成把握相信这是苹果哈哈哈。
> 
> 准确来说，这个SCN的类比应该是，先给小孩看了100张苹果占大多数的图片，下一次再给他看一张椅子或者一张特别糊的照片，你告诉他是苹果，他觉得不对劲了再自己纠正过来😂
> 
> 但是你先给他看的那100张图片，假如其中苹果有50张，另50张是其他各种东西的，而且还是乱序给他看的，效果是不是就emm

感謝您的回覆~
如果按照您的解釋一開始10個 epoch 也是需要相較於乾淨的data 去訓練模型吧?不然穩定就像您說的不會那麼好了。

**Comment by UEFI-code** [comment]
> > > 不需要标记，自我感知哪些是uncertainty，举个例子，你教小孩看了100张苹果的图片，下一次，你给他看一张椅子或者一张特别糊的照片，你告诉他是苹果，你觉得她会有几成把握相信这是苹果哈哈哈。
> > 
> > 
> > 准确来说，这个SCN的类比应该是，先给小孩看了100张苹果占大多数的图片，下一次再给他看一张椅子或者一张特别糊的照片，你告诉他是苹果，他觉得不对劲了再自己纠正过来😂
> > 但是你先给他看的那100张图片，假如其中苹果有50张，另50张是其他各种东西的，而且还是乱序给他看的，效果是不是就emm
> 
> 感謝您的回覆~
> 如果按照您的解釋一開始10個 epoch 也是需要相較於乾淨的data 去訓練模型吧?不然穩定就像您說的不會那麼好了。

是的，data里面错误东西不能太多，而且还有运气成分，比如刚一开始的10个epoch使用了错误data的情况。

**Comment by hsiehchungting** [comment]
> > > > 不需要标记，自我感知哪些是uncertainty，举个例子，你教小孩看了100张苹果的图片，下一次，你给他看一张椅子或者一张特别糊的照片，你告诉他是苹果，你觉得她会有几成把握相信这是苹果哈哈哈。
> > > 
> > > 
> > > 准确来说，这个SCN的类比应该是，先给小孩看了100张苹果占大多数的图片，下一次再给他看一张椅子或者一张特别糊的照片，你告诉他是苹果，他觉得不对劲了再自己纠正过来😂
> > > 但是你先给他看的那100张图片，假如其中苹果有50张，另50张是其他各种东西的，而且还是乱序给他看的，效果是不是就emm
> > 
> > 
> > 感謝您的回覆~
> > 如果按照您的解釋一開始10個 epoch 也是需要相較於乾淨的data 去訓練模型吧?不然穩定就像您說的不會那麼好了。
> 
> 是的，data里面错误东西不能太多，而且还有运气成分，比如刚一开始的10个epoch使用了错误data的情况。
> 另外，alpha应该是“先入为主”的决定原理，这就像你读一本书之前先评估它对你的意义，如果你觉得不重要可能就不读了。（前提是你之前有一定经验）

非常感謝您的解釋
我之前也對alpha帶有疑惑，對於alpha的定義。所以也許也會被誤判的問題。
