### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by fengyuanzuo** [kaiwang960112/Self-Cure-Network#28]
请问作者LFW数据集可以应用于自愈网络么，您说的数据申请没通过，或者用自己数据需要制作成什么格式呢

**Comment by kaiwang960112** [comment]
分类的都可以试试 想看效果的话 可以手动加一下flip的noises去看看。数据集？你说的是affectnet ferplus和rafdb那些嘛？

**Comment by fengyuanzuo** [comment]
感谢您百忙中的回复，您在GitHub上说明的是
raf-db人脸表情数据库，我对您所提自愈网络(SCN)非常感兴趣，但是该数据库我申请后很久并没有回复，所以想请教一下您如果用自己的一些数据，那么txt里面的内容格式该如何布置，或者如果可以的话可否给我发一下数据制作样式呢
2020-10-26 

1970823 



发件人："Kai Wang (Victor Kai)" <notifications@github.com>
发送时间：2020-10-26 11:32
主题：Re: [kaiwang960112/Self-Cure-Network] 关于数据集 (#28)
收件人："kaiwang960112/Self-Cure-Network"<Self-Cure-Network@noreply.github.com>
抄送："fengyuanzuo"<1970823@stu.neu.edu.cn>,"Author"<author@noreply.github.com>

分类的都可以试试 想看效果的话 可以手动加一下flip的noises去看看。数据集？你说的是affectnet ferplus和rafdb那些嘛？

**Comment by YXH-YXH** [comment]
想问一下RAF-DB数据集你目前申请的怎么样了？
我也尝试了申请，但是目前还没有回复。
FERPlus数据集已经获得，但是不清楚如何在此项目中使用

**Comment by fengyuanzuo** [comment]
没用回复，已经放弃了

2020-12-28 颤三

1970823 



发件人：YXH-YXH <notifications@github.com>
发送时间：2020-12-28 20:30
主题：Re: [kaiwang960112/Self-Cure-Network] 关于数据集 (#28)
收件人："kaiwang960112/Self-Cure-Network"<Self-Cure-Network@noreply.github.com>
抄送："fengyuanzuo"<1970823@stu.neu.edu.cn>,"Author"<author@noreply.github.com>

想问一下RAF-DB数据集你目前申请的怎么样了？
我也尝试了申请，但是目前还没有回复。
FERPlus数据集已经获得，但是不清楚如何在此项目中使用

**Comment by kaiwang960112** [comment]
rafdb数据集有版权的，所以我也不敢在没有权限的情况下给你们。两三年前，我当时发邮件申请的时候，那边回复的很快呀。不过我申请北邮那个rafdb2.0，就是带au的那个，也是五六个月没有回复-------- 原始邮件 --------发件人： fengyuanzuo <notifications@github.com>日期： 2020年12月28日周一 晚上8:38收件人： kaiwang960112/Self-Cure-Network <Self-Cure-Network@noreply.github.com>抄送： "Kai Wang (Victor Kai)" <kai.wang960112@gmail.com>, Comment <comment@noreply.github.com>主    题： Re: [kaiwang960112/Self-Cure-Network] 关于数据集 (#28)

没用回复，已经放弃了







2020-12-28 颤三







1970823 















发件人：YXH-YXH <notifications@github.com>



发送时间：2020-12-28 20:30



主题：Re: [kaiwang960112/Self-Cure-Network] 关于数据集 (#28)



收件人："kaiwang960112/Self-Cure-Network"<Self-Cure-Network@noreply.github.com>



抄送："fengyuanzuo"<1970823@stu.neu.edu.cn>,"Author"<author@noreply.github.com>







想问一下RAF-DB数据集你目前申请的怎么样了？



我也尝试了申请，但是目前还没有回复。



FERPlus数据集已经获得，但是不清楚如何在此项目中使用

**Comment by twinsyssy1018** [comment]
你好 请问自己的原始图片经过人脸检测后，需要做哪些图像处理 人脸对齐的方法是什么呢？

**Comment by Wiikk** [comment]
@fengyuanzuo  您好，请问后来收到回复了吗? 需要等多久呢
