### ISSUE TITLE
About RRLoss

### ISSUE THREAD

**Issue by Haiyang21** [kaiwang960112/Self-Cure-Network#3]
1. Is it the dim of alpha[i] is 1x1 which comes from sigmoid ?
2. Do you know what is the reason of RRLoss always being 0, since (alphaH - alphaL) > margin almostly. (margin is 0.15)

Thanks.

**Comment by kaiwang960112** [comment]
1. yes
2. because of the constraint is so weak (mean value of \alpha_H, \alpha_L). We will explore some stronger constraints in the future.
Thank you.
