### ISSUE TITLE
Where can I find the WebEmotion Dataset?

### ISSUE THREAD

**Issue by ilovecv** [kaiwang960112/Self-Cure-Network#30]
Hi,

May I know when the WebEmotion Dataset will be released? Thank you very much!

**Comment by youcaiSUN** [comment]
Hello kai,

Thanks for your kind sharing. Since the cvpr ddl has passed for several months, I want to ask when will you release the code for downloading WebEmotion dataset?

**Comment by kaiwang960112** [comment]
hello, I am very busy for the last several months. And now I have completed my Ph.D application. The code will be coming soon.
