### ISSUE TITLE
关于rafdb与ferflus训练

### ISSUE THREAD

**Issue by okwly** [kaiwang960112/Self-Cure-Network#31]
想请教大佬，在rafdb、ferplus训练过程中有使用数据平衡采样等方法克服数据不平衡问题吗？在用IR网络复现时我出现了开始重标签后val loss升高， Val acc降低的问题，想问问可能是什么原因呢？

**Comment by kaiwang960112** [comment]
重标签后loss短暂性升高是正常的，如果一直升的话 说明你可能选择的relabel节点不合适

okwly <notifications@github.com> 於 2020年11月19日週四 下午11:12寫道：
