### ISSUE TITLE
关于train.py中relabel模块的代码问题

### ISSUE THREAD

**Issue by Suimingzhe** [kaiwang960112/Self-Cure-Network#33]
首先感谢作者的代码分享！

代码中关于relabel模块中，论文里提到只考虑low-importance group中进行relabel，但在代码中sm值是对整个outputs进行softmax，包括了high-importance group，这里是否应该修改？（虽然可能训练集中存在的uncertain图片可能全部集中在low-importance group中）

最后再次感谢作者的分享，另外可以再分享一些您其他的关于FER的论文么，谢谢。

**Comment by kaiwang960112** [comment]
new_update_idx = torch.from_numpy(np.intersect1d(down_idx.cpu().numpy(), update_idx.cpu().numpy())) 把这句加在update_idx = true_or_false.nonzero().squeeze()之后一行。

**Comment by Yiqin-Luo** [comment]
您好！请问您还保存了SCN的完整代码么？可以分享一下么？非常感谢！
