### ISSUE TITLE
关于ferplus的准确率

### ISSUE THREAD

**Issue by hfutly66** [kaiwang960112/Self-Cure-Network#34]
您好，感谢您分享的代码。但是我在训练的时候发现对于ferplus数据集，准确率只达到了83%，想请教原因。
对于ferplus的标签，我的方法是取其中的最大值。其他都是正常训练

**Comment by bohelion** [comment]
> 您好，感谢您分享的代码。但是我在训练的时候发现对于ferplus数据集，准确率只达到了83%，想请教原因。
> 对于ferplus的标签，我的方法是取其中的最大值。其他都是正常训练

您好，能分享一下您训练ferplus数据集的代码吗？非常感谢！353099145@qq.com

**Comment by dyt0414** [comment]
> 您好，感谢您分享的代码。但是我在训练的时候发现对于ferplus数据集，准确率只达到了83%，想请教原因。
> 对于ferplus的标签，我的方法是取其中的最大值。其他都是正常训练

请问您是直接用作者提供的train.py放入ferplus的数据集吗？我这样做，得到的准确率只有60%左右，请问可以指导一下吗？

**Comment by zhaijianyang** [comment]
您好，能分享一下您训练ferplus数据集的代码吗？非常感谢！1240758677@qq.com

**Comment by hsiehchungting** [comment]
> 您好，感谢您分享的代码。但是我在训练的时候发现对于ferplus数据集，准确率只达到了83%，想请教原因。
> 对于ferplus的标签，我的方法是取其中的最大值。其他都是正常训练

大神您好 能分享一下您训练ferplus数据集的代码吗？非常感谢！ chungting093777@gmail.com

**Comment by kaiwang960112** [comment]
那应该没问题呀

Jetson nano basic install ***@***.***> 於 2021年4月19日週一
下午5:11寫道：

**Comment by yuebaitianqing** [comment]
> > 您好，感谢您分享的代码。但是我在训练的时候发现对于ferplus数据集，准确率只达到了83%，想请教原因。
> > 对于ferplus的标签，我的方法是取其中的最大值。其他都是正常训练
> 
> 请问您是直接用作者提供的train.py放入ferplus的数据集吗？我这样做，得到的准确率只有60%左右，请问可以指导一下吗？

60%可能是数据集的问题吧，看看是不是没读取好。

**Comment by 1617226214** [comment]
@yuebaitianqing 请问你的问题解决了么，我利用作者提供的预训练模型参数加载进去后，准确率也一直只能达到83%到不了论文上的88%。

**Comment by yuebaitianqing** [comment]
> @yuebaitianqing 请问你的问题解决了么，我利用作者提供的预训练模型参数加载进去后，准确率也一直只能达到83%到不了论文上的88%。

88%没复现出来，但我后来修改了标签值，用ferplus那个官方代码里的方法生成了新的标签文件，效果好了一点点，好像到85%了吧

**Comment by 1617226214** [comment]
> > @yuebaitianqing 请问你的问题解决了么，我利用作者提供的预训练模型参数加载进去后，准确率也一直只能达到83%到不了论文上的88%。
> 
> 88%没复现出来，但我后来修改了标签值，用ferplus那个官方代码里的方法生成了新的标签文件，效果好了一点点，好像到85%了吧

我也是用的官方的代码来合并fer2013和ferplus的csv文件，方便发一份你的合成文件代码给我么。谢谢！1617226214@qq.com

**Comment by dyt0414** [comment]
我用了作者的另一篇论文RAN中的FERplus的数据目录，跑出来只有87左右，并没有论文中的89。同时用AffectNet数据集训练，也只有55左右的正确率，无法到达论文中的60

**Comment by userguazi** [comment]
您好，能分享一下您训练ferplus数据集的代码吗？非常感谢！1223182881@qq.com

**Comment by 1102998363** [comment]
您好，能分享一下您训练ferplus数据集的代码吗？非常感谢！[1102998363@qq.com](mailto:1102998363@qq.com)
