### ISSUE TITLE
关于训练过程中的问题

### ISSUE THREAD

**Issue by MandoraCC** [kaiwang960112/Self-Cure-Network#35]
大佬，我对训练结果有疑问啊！
1. 使用RAF-DB数据集，且直接使用论文提供的train.py文件运行（即使用SCN网络），精度能达到84%，与论文Table 4的实验结果的数据78.31相差太大了。
2. 对RAF-DB数据集的训练集的每个类别更改10%的label，同样使用SCN网络，运行结果精度能达到82%，与论文Table 2中70.26%的结果相差也大了。
最后！求大佬给我发个论文中提到的Ms-Celeb-1M上的人脸识别预训练模型！多谢了！！！

**Comment by MaQingya** [comment]
你好，你是如何申请到RAF-DB数据集的，为什么我发邮件申请一直被退回？

**Comment by MandoraCC** [comment]
> 你好，你是如何申请到RAF-DB数据集的，为什么我发邮件申请一直被退回？

**Comment by Carlyx** [comment]
> 大佬，我对训练结果有疑问啊！
> 
> 1. 使用RAF-DB数据集，且直接使用论文提供的train.py文件运行（即使用SCN网络），精度能达到84%，与论文Table 4的实验结果的数据78.31相差太大了。
> 2. 对RAF-DB数据集的训练集的每个类别更改10%的label，同样使用SCN网络，运行结果精度能达到82%，与论文Table 2中70.26%的结果相差也大了。
>    最后！求大佬给我发个论文中提到的Ms-Celeb-1M上的人脸识别预训练模型！多谢了！！！

您好，我申请RAF-DB数据作者没有回复，请问可以给一个链接嘛

**Comment by kaiwang960112** [comment]
你的实验参数发一下？我看看

发自我的iPhone
