### ISSUE TITLE
训练过拟合

### ISSUE THREAD

**Issue by PanXiangshuai** [kaiwang960112/Self-Cure-Network#38]
你好，我是深度学习的小萌新，按照你的步骤来训练，训练集12271图片，测试集3068，但是到了11epoch训练准确率猛增，后面就百分百了，怎么改正呀，谢谢。

**Comment by kaiwang960112** [comment]
hello，你可能把测试集合加进去了

PanXiangshuai ***@***.***> 於 2021年3月26日週五 下午4:48寫道：

**Comment by twinsyssy1018** [comment]
我也是到11epoch开始出现问题 过拟合了![image](https://user-images.githubusercontent.com/14009379/114660640-3cd86780-9d28-11eb-963c-9f54be7f1ba2.png)

**Comment by dzz416** [comment]
楼主可以吧数据集共享一下吗，我没有训练数据集
