### ISSUE TITLE
dataset will be open source？

### ISSUE THREAD

**Issue by erquren** [kaiwang960112/Self-Cure-Network#4]
i want to try it.

**Comment by kaiwang960112** [comment]
The dataset will be public to the research community free. Thank you for your interest.

**Comment by Karin-S** [comment]
Kindly asking that if the dataset is pubilc now?

**Comment by kaiwang960112** [comment]
Thanks. I am writing my thesis these days, the code will public as soon as
possible. Thanks again.

Shuang <notifications@github.com> 於 2020年4月7日週二 下午4:54寫道：

**Comment by kaiwang960112** [comment]
> Kindly asking that if the dataset is pubilc now?

the dataset size is about 500g, during the COVID-19, I have no access to my lab. When I have access, I will opensource this dataset. Good luck.

**Comment by ilovecv** [comment]
@kaiwang960112 Hi, May I know when the dataset will be available? I am wondering if you can share the URL of the videos first considering the dataset is a bit large? Thanks!

**Comment by Karin-S** [comment]
@kaiwang960112 Hi, I am here again. Just wonder that have you arrived your lab? I want to follow your experiment. Thanks!

**Comment by kaiwang960112** [comment]
OK，I have arrived at my lab发自我的华为手机-------- 原始邮件 --------发件人： Shuang <notifications@github.com>日期： 2020年5月12日周二 下午4:24收件人： kaiwang960112/Self-Cure-Network <Self-Cure-Network@noreply.github.com>抄送： "Kai Wang (Victor Kai)" <kai.wang960112@gmail.com>, Mention <mention@noreply.github.com>主    题： Re: [kaiwang960112/Self-Cure-Network] dataset will be open source？ (#4)
@kaiwang960112 Hi, I am here again. Just wonder that have you arrived your lab? I want to follow your experiment. Thanks!

**Comment by kaiwang960112** [comment]
code is opensource now
