### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by charmlleno** [kaiwang960112/Self-Cure-Network#40]
Hi, I am a master's student of Computer Science and Information Engineering at Chung Hua University, and I came across your paper about Self Cure Network. I am trying to run your program but I am stuck with this problem. I hope you can help me. I already tried reinstalling the CUDA but still, nothing works. I hope someone can help me asap. Thank you in advance.

**Comment by kaiwang960112** [comment]
可以把具体报错发一下？

charmlleno ***@***.***> 於 2021年4月4日週日 下午6:32寫道：

**Comment by kaiwang960112** [comment]
你的conda和你的cuda版本应该不匹配，你下载一下匹配版本的conda哈

**Comment by charmlleno** [comment]
thank you. I already fix the problem and done with the training for the Raf-db dataset. May I know how can I be able to run the testing? thank you.
