### ISSUE TITLE
预训练模型解压失败

### ISSUE THREAD

**Issue by siyue-coder** [kaiwang960112/Self-Cure-Network#43]
您好，我在SCN主页下载的预训练模型解压失败，显示文件已损坏，能重新发一下预训练模型吗，十分感谢

**Comment by kaiwang960112** [comment]
ok,之前大家都是可以用的呀，有点奇怪，我过几天找一下之前的旧电脑更新一下

siyue-coder ***@***.***> 於 2021年4月14日週三 上午9:46寫道：

**Comment by siyue-coder** [comment]
好的好的，十分感谢您发自我的荣耀手机-------- 原始邮件 --------发件人： "Kai Wang (Victor Kai)" ***@***.***>日期： 2021年4月14日周三 中午12:45收件人： kaiwang960112/Self-Cure-Network ***@***.***>抄送： siyue-coder ***@***.***>, Author ***@***.***>主    题： Re: [kaiwang960112/Self-Cure-Network] 预训练模型解压失败 (#43)

ok,之前大家都是可以用的呀，有点奇怪，我过几天找一下之前的旧电脑更新一下







siyue-coder ***@***.***> 於 2021年4月14日週三 上午9:46寫道：

**Comment by kaiwang960112** [comment]
我检查过了 不用解压 直接torch load就好了

**Comment by siyue-coder** [comment]
好的好的，谢谢您发自我的荣耀手机-------- 原始邮件 --------发件人： "Kai Wang (Victor Kai)" ***@***.***>日期： 2021年4月28日周三 下午3:35收件人： kaiwang960112/Self-Cure-Network ***@***.***>抄送： siyue-coder ***@***.***>, Author ***@***.***>主    题： Re: [kaiwang960112/Self-Cure-Network] 预训练模型解压失败 (#43)

我检查过了 不用解压 直接torch load就好了

**Comment by kaiwang960112** [comment]
不用客气，记得close issue

siyue-coder ***@***.***> 於 2021年4月28日週三 下午3:37寫道：
