### ISSUE TITLE
想尋求SCN 關於AffectNet 與fer+的實現代碼

### ISSUE THREAD

**Issue by hsiehchungting** [kaiwang960112/Self-Cure-Network#44]
您好~
我從github上看到大老所寫的論文與提供的code目前有成功運用rafdb，但論文中還有兩種資料集的結果。有於是深度學習新手所以對那兩類資料如何處理與讀取相當陌生，希望能取的大老的代碼參考並實作看看
由衷感謝大大 
chungting093777@gmail.com

**Comment by qiang333** [comment]
> 您好~ 我從github上看到大老所寫的論文與提供的code目前有成功運用rafdb，但論文中還有兩種資料集的結果。有於是深度學習新手所以對那兩類資料如何處理與讀取相當陌生，希望能取的大老的代碼參考並實作看看 由衷感謝大大 [chungting093777@gmail.com](mailto:chungting093777@gmail.com)

你好，请问下你最后affectnet 和 fer+怎么处理的，遇到了和你一样的困难
