### ISSUE TITLE
test.py含义

### ISSUE THREAD

**Issue by lujiazhou** [kaiwang960112/Self-Cure-Network#45]
想请问一下代码中test.py运行输出的(time2 - time1) * 1000, (time3 - time2) * 1000, (time3 - time1) * 1000)是什么含义，求解

**Comment by zzx820302704** [comment]
请问您知道是什么含义了吗？

**Comment by GuopingZ** [comment]
两个时间差太小，乘以1000使得数据更方便读，比如time2-time1=0.002155, 乘以1000后是2.155，就可以读作二点一五毫秒
