### ISSUE TITLE
关于预训练模型的问题

### ISSUE THREAD

**Issue by xiaoliaobin** [kaiwang960112/Self-Cure-Network#58]
你好，我想请问一下你的ijba_res18_naive.path.tar预训练模型是使用MS-Celeb-1M数据集预训练的ResNet18？还是用你的SCN训练过的？我想要一份MS-Celeb-1M数据集预训练的ResNet18模型。

**Comment by kaiwang960112** [comment]
这是用resnet18训的

发自我的iPhone

**Comment by xiaoliaobin** [comment]
我想请问一下为什么我仅用预训练过的ResNet18跑Raf-DB准确率能达到88%？

**Comment by kaiwang960112** [comment]
强~

发自我的iPhone

**Comment by LiZhiHao97** [comment]
事实上，我在使用了数据增强后，在res18的baseline上，达到了89.3的惊人效果。数据增强与预训练，貌似对FER的增幅很大。

**Comment by kaiwang960112** [comment]
这个也是很强的，性能刷的飞起

发自我的iPhone

**Comment by LiZhiHao97** [comment]
> > 事实上，我在使用了数据增强后，在res18的baseline上，达到了89.3的惊人效果。数据增强与预训练，貌似对FER的增幅很大。
> 
> 你好，我想请问你的预训练是用imagenet还是MS-Celeb-1M，我用前者只能达到86.4，用后者产生过拟合。另外你的数据增强方式是什么，希望不吝赐教。

是在MS-Celeb-1M上预训练的，就是作者提供的ijba_res18_naive.path.tar

**Comment by LiZhiHao97** [comment]
@yangjian1218 @likerapkeyboard 重新看了下作者的代码，貌似只加了随机擦除，我测试的时候加的比较多，用了水平翻转、颜色抖动、角度旋转、随机擦除

**Comment by bigcash** [comment]
> 

提醒一下，作者在60、74行有其他的增强，随机翻转、加高斯噪音
不过我训练RAF-DB一直是86%+，到不了87%啊，可能是因为我的batch_size是64的原因？
另外，我直接加载作者提供的pretrain model，在RAF-DB的测试集上测试，acc=0.2216，这么低，不知道为什么，我哪里搞错了吗？请教一下

**Comment by bigcash** [comment]
> @yangjian1218 @likerapkeyboard 重新看了下作者的代码，貌似只加了随机擦除，我测试的时候加的比较多，用了水平翻转、颜色抖动、角度旋转、随机擦除
提醒一下，作者在60、74行有其他的增强，随机翻转、加高斯噪音
不过我训练RAF-DB一直是86%+，到不了87%啊，可能是因为我的batch_size是64的原因？
另外，我直接加载作者提供的pretrain model，在RAF-DB的测试集上测试，acc=0.2216，这么低，不知道为什么，我哪里搞错了吗？请教一下

**Comment by bigcash** [comment]
> @yangjian1218 @likerapkeyboard 重新看了下作者的代码，貌似只加了随机擦除，我测试的时候加的比较多，用了水平翻转、颜色抖动、角度旋转、随机擦除

提醒一下，作者在60、74行有其他的增强，随机翻转、加高斯噪音
不过我训练RAF-DB一直是86%+，到不了87%啊，可能是因为我的batch_size是64的原因？
另外，我直接加载作者提供的pretrain model，在RAF-DB的测试集上测试，acc=0.2216，这么低，不知道为什么，我哪里搞错了吗？请教一下

**Comment by LiZhiHao97** [comment]
@bigcash 你说的是对的，确实还有其他的增强，我之前看的时候看漏了。
按作者在readme所说，将margin_1=0.07在64的batch_size下能够达到margin=0.15，batch_size=1024类似的效果，不清楚你有没有修改batch_size的值。
作者提供的预训练模型是在MS-celeb预训练的，并不是SCN跑出来的结果，你需要加载后在SCN上进行微调。

**Comment by RockPine520** [comment]
> 事实上，我在使用了数据增强后，在res18的baseline上，达到了89.3的惊人效果。数据增强与预训练，貌似对FER的增幅很大。

我在做实验的时候也发现了这个现象。但是很多benchmark似乎都没有达到这个效果，不知道是什么原因

**Comment by 759176395-eng** [comment]
你好，现在好像看不到ijba_res18_naive.path.tar这个文件了，可以重新提供一下吗？

**Comment by kaiwang960112** [comment]
应该无了，sorry

759176395-eng ***@***.***> 于2025年12月19日周五 17:02写道：

**Comment by 759176395-eng** [comment]
没关系，谢谢
