### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by xnmamwdjb** [kaiwang960112/Self-Cure-Network#59]
您好，我在readme最后的link里面下载的预训练模型ijba_res18_naive.path.tar，用test.py运行之后提示KeyError: 'model_state_dict'，请问这个怎么处理？

**Comment by bigcash** [comment]
使用train.py中的load pretrain的代码可以加载这个预训练模型。
不过我使用这种方式加载预训练模型后，直接在RAF-DB的测试集中测试，acc只有0.2216，不知道是什么情况

**Comment by bigcash** [comment]
额，实际测试了一下，这种方式虽然不报错，但结果好像不对，所有预测的结果都是predicts=1。还是另外再找方法吧

**Comment by bigcash** [comment]
ijba_res18_naive.path.tar模型是ijba在人脸识别中的模型，作者用这个来作为模型初始化参数的，所以这个不是本项目的结果模型，所以刚才我说的load模型的方式，是没有问题的
