### ISSUE TITLE
Reproducible results

### ISSUE THREAD

**Issue by amirhfarzaneh** [kaiwang960112/Self-Cure-Network#6]
Hello. Great work on this and the RAN framework. I was wondering how you make sure your results are reproducible with PyTorch? What is the standard deviation of your results? Do you get a large standard deviation on training baseline models such as ResNet-18 on RAF-DB or AffectNet?

**Comment by kaiwang960112** [comment]
Hi, Good question. In the RAN framework, I have uploaded the models on google driver.
Recently, I will release SCN codes.
Thank you.

**Comment by kaiwang960112** [comment]
SCN code is opensource
