### ISSUE TITLE
使用ijba_res18_naive.pth.tar预训练，结果出现过拟合

### ISSUE THREAD

**Issue by zzzzzzyang** [kaiwang960112/Self-Cure-Network#60]
第一次运行，按照代码中默认的imageNet初始化，训练结果最高86.4，第二次使用您提供的ijba_res18_naive.pth.tar初始化，从第11个epoch开始出现严重过拟合，最终只有62，未修改其他任何代码。浏览issues发现有不少同学都遇到这个问题，麻烦您能够提供一个解决思路吗？

**Comment by ming1993li** [comment]
请问一下这个ijba_res18_naive.pth.tar 是在resent18在MS-Celeb-1M上的预训练模型吗？还是作者最终的模型？

**Comment by kaiwang960112** [comment]
这是预训练模型哈
