### ISSUE TITLE
align图片格式要求

### ISSUE THREAD

**Issue by yangjian1218** [kaiwang960112/Self-Cure-Network#61]
由于申请数据集比较难,我从网络上下载的数据集,是原图,没有进行align.数据集下分7个不同表情的子文件夹,
1.请问作者用什么方法进行人脸检测align,尺寸为多少? 
2.我用retinaface人脸检测,insightface的align到112x112是否可以?
3.另外那个标签格式 是不是就是:图片地址 + 标签?

**Comment by qiang333** [comment]
> 另外问一下,人脸需要扣出来么 我看主页的人脸好像从背景扣出来了

你好，请问下你的人脸对齐问题解决了嘛
