### ISSUE TITLE
Would you mind sharing the 0.3noise_train.txt?

### ISSUE THREAD

**Issue by MalonoCN** [kaiwang960112/Self-Cure-Network#62]
To make a fair comparison with your nice work, I need the 0.3noise_train.txt used in your paper. Would mind sharing it with us?

**Comment by kaiwang960112** [comment]
Just write a python code to ensure that there 30% labels are inconsistent
with the original label. Thx

MalonoCN ***@***.***>于2021年11月8日 周一下午9:21写道：

**Comment by MalonoCN** [comment]
As we know, it's very simple to do that. If you don't have the original 0.3noise_train.txt, I will re-generate one to compare your method. Thanks for your quick reply.

**Comment by kaiwang960112** [comment]
Yep go ahead. I have moved to NUS，so I do not have the original file

发自我的iPhone

**Comment by MalonoCN** [comment]
Congratulations！Thanks again.
