### ISSUE TITLE
Question about the parameter β

### ISSUE THREAD

**Issue by seekFire** [kaiwang960112/Self-Cure-Network#66]
Thank U for your excellent work!
I have read your paper and modified some code in this repo so as to train models using my own dataset. You know the parameter β represents the ratio of high-importance group in total data. So I just wonder if I don't know how much low-importance sample in my dataset in advance, should I set β with multiple values and test it one by one, or set β as a learnable parameter like δ1 ?

**Comment by kaiwang960112** [comment]
maybe setting the \beta with multiple ones looks interesting. You can have a try. I believe the more fine-grained divide the batch can lead the further improvement of SCN.
