### ISSUE TITLE
关于人工噪音实验

### ISSUE THREAD

**Issue by zzzzzzyang** [kaiwang960112/Self-Cure-Network#69]
请问作者，人工噪音实验中的结果你提供的是训练过程中的最大acc吗？我看了几个您这篇后续的相关工作，他们的噪音实验结果是均值±方差的形式，
有的是记录每次实验最后一个epoch的acc，然后多次实验求均值方差，
有的是记录每次实验最后10个或最后5个epoch的平均acc，然后多次实验求均值方差，
请问关于噪音实验的结果有统一的标准吗？

**Comment by likerapkeyboard** [comment]
如果没有统一标准，您更推荐哪种呢？非常感谢！

**Comment by kaiwang960112** [comment]
我觉得两种都行，如果最好的或者平均下来只有一种可以明显超过别人，我觉得都是方法提升不明显。最好是两种统计形式都可以明显提升才是最好的

likerapkeyboard ***@***.***>于2022年4月18日 周一下午12:10写道：

**Comment by likerapkeyboard** [comment]
好的，感谢您的回答！还是想确认一下您论文了的结果是最好acc吧？

**Comment by kaiwang960112** [comment]
是的
