### ISSUE TITLE
关于人脸预训练模型

### ISSUE THREAD

**Issue by zengqi0730** [kaiwang960112/Self-Cure-Network#7]
论文里提到人脸预训练模型对SCN精度提升非常大，不知可否提供这个预训练模型呢？

**Comment by kaiwang960112** [comment]
这个在我的TIP文章里面有，用的同一个模型。请看上一个github，弱监督的那个数据库后期会开源

**Comment by zengqi0730** [comment]
我尝试复现论文，训练结果如下：
Weight   Rank    Relabel     RAF-DB   RAF-DB(pretrain)
  X            X             X           70.96          X
  X            X             V           70.70          X
  X            V             X           71.68          X
  V            X             X           71.00          X
  V            V             X           71.74          X
  V            V             V           71.84          X

由于没找到预训练模型的下载链接，没试验RAF-DB(pretrain)。用的单卡1080ti，batchsize=256，参数略有不同，初始学习率0.01,  60轮训练，每隔10轮 lr = lr*0.4，第40轮开始relabel，其他的参数和论文一致。
我的运行结果跟原论文里的结果差距有点大，提升并不明显，希望博主能尽快开源，还有能否给下预训练模型的下载链接，我在网上没找到，谢谢！

**Comment by kaiwang960112** [comment]
这是在10%noise下的结果？还是

**Comment by zengqi0730** [comment]
没有noise，直接在原训练集basic/test的运行结果，应该是对应文中的Table5

**Comment by kaiwang960112** [comment]
输入大小多大？用的什么网络？

**Comment by zengqi0730** [comment]
用的官方的resnet18，输入224*224
还是等大佬开源吧，今天各种尝试，最高到74.5，
然后下载了ijba_res18_naive.pth.tar这个模型，固定卷积层，关闭relabel模块，打开另外两个，只训练后面两个全连接层，准确率71不到，全部放开训，76左右，但远不到80。
大佬早点开源吧，膜拜下单模型87 88是如何达到的

**Comment by kaiwang960112** [comment]
最近在写毕业论文，我找时间发个模型你测测哈哈-------- 原始邮件 --------发件人： zengqi0730 <notifications@github.com>日期： 2020年3月26日周四 晚上9:50收件人： kaiwang960112/Self-Cure-Network <Self-Cure-Network@noreply.github.com>抄送： "Kai Wang (Victor Kai)" <kai.wang960112@gmail.com>, Comment <comment@noreply.github.com>主    题： Re: [kaiwang960112/Self-Cure-Network] 关于人脸预训练模型 (#7)
用的官方的resnet18，输入224*224
还是等大佬开源吧，今天各种尝试，最高到74.5，
然后下载了ijba_res18_naive.pth.tar这个模型，固定卷积层，关闭relabel模块，打开另外两个，只训练后面两个全连接层，准确率71不到，全部放开训，76左右，但远不到80。
大佬早点开源吧，膜拜下单模型87 88是如何达到的

**Comment by zengqi0730** [comment]
感谢大佬，我的邮箱zengqi0730@163.com

**Comment by kaiwang960112** [comment]
你给我发一份email，我刚刚写了一下代码（由于实验室年底换集群，硬盘在深圳，无法找到原始代码，所以近期一直没整理，因为我人无法回到深圳）你既然提出了疑问，我就重写了一下。跑了一版，结果跟论文是相近的。我们具体wechat沟通，我会在回复你的email里告诉你我的wechat。谢谢对我们工作的关注。

**Comment by zlweiyang** [comment]
您好，很感谢您之前的RAN那篇文章的的开源代码，一直在关注您的研究，最近在尝试复现您的代码，但是还没跑出复现出来，能否参考一下您最近的代码，我的邮箱是2530997324@qq.com

**Comment by kaiwang960112** [comment]
你是说SCN的code吗？还是RAN？最近在写毕业论文，人也一直没能回到深圳，等整理好会开源的。

**Comment by zlweiyang** [comment]
SCN的代码


 
---原始邮件---
发件人: "Kai Wang (Victor Kai)"<notifications@github.com&gt;
发送时间: 2020年4月6日 02:36:29
收件人: "kaiwang960112/Self-Cure-Network"<Self-Cure-Network@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"zhuliang"<2530997324@qq.com&gt;;
主题: Re: [kaiwang960112/Self-Cure-Network] 关于人脸预训练模型 (#7)




 你是说SCN的code吗？还是RAN？最近在写毕业论文，人也一直没能回到深圳，等整理好会开源的。

**Comment by skywangch** [comment]
为什么我用baseline方式训出来的模型测试率最高能达到80%，难道我的测试方式有问题吗？

**Comment by kaiwang960112** [comment]
那可能确实有些问题，我近期就会回实验室，整理好会开源的哈

**Comment by kaiwang960112** [comment]
代码已经开源

**Comment by zimuyuan** [comment]
作者您好，您在RAN里面分享了ResNet18的人脸预训练模型，请问这个模型预训练是自己训练的吗？如果不是那是在哪里下载的呢？然后还有别的例如ResNet34，或者ResNet50的人脸预训练模型吗？

**Comment by kaiwang960112** [comment]
可以在RAN那个网页上，下拉到最后，有个link，点击进入下载

**Comment by zimuyuan** [comment]
RAN最下面的那个链接我打不开，可能是要翻墙吧。请问这个模型预训练是自己训练的吗？如果不是那是在哪里下载的呢？然后还有别的例如ResNet34，或者ResNet50的人脸预训练模型吗？

**Comment by kaiwang960112** [comment]
你可以直接拿imagenet预训练模型来微调，可能需要翻墙吧，我们训resnet34以及后面的那些

**Comment by zimuyuan** [comment]
好的，谢谢！！

**Comment by duchengyao** [comment]
大佬牛逼

**Comment by SJHNJU** [comment]
您好，请问SCN使用的，在ms-celeb-1m上预训练的模型可以也发我一份吗，邮箱
151180108@smail.nju.edu.cn，非常感谢！！

**Comment by kaiwang960112** [comment]
这个模型在ran那个github链接里面有，我的github里面那个challenging condition fer那个开源里面有

**Comment by lycwgf** [comment]
您好，预训练模型是在哪里下载的？

**Comment by lycwgf** [comment]
您好，关于人脸预训练模型，我使用https://github.com/Xiaoccer/MobileFaceNet_Pytorch上mobilefacenet预训练模型，大小4M左右，精度只能达到77%，这个跟预训练模型关系很大吗？
