### ISSUE TITLE
有关rafdb数据集调参和测试的问题

### ISSUE THREAD

**Issue by RockPine520** [kaiwang960112/Self-Cure-Network#70]
作者您好！
我想请问一下，rafdb数据集缺少验证集，我们在做实验的时候需要自己从训练集划分出验证集进行调参，然后用测试集进行测试吗？还是说不需要这个步骤，直接在测试集上调参，得到最好的结果就行了？
AffectNet数据集也有同样的问题，希望作者您能解答一下我的疑惑，非常感谢！

**Comment by kaiwang960112** [comment]
直接对着测试集调可以，也可以先从rafdb训练集里面分出一些数据做验证集，然后调参。最后在测试集上测测。随机分出一些数据哈，应该是同分布的。affectnet也可以这么做哈。

RockPine520 ***@***.***>于2022年5月1日 周日下午5:10写道：

**Comment by RockPine520** [comment]
谢谢作者答复！因为我看一些资料说对着测试集调参会出现信息泄露的问题，所以产生了这方面的疑惑

**Comment by kaiwang960112** [comment]
个人觉得只要不拿测试集去训练应该都问题不大

RockPine520 ***@***.***>于2022年5月1日 周日下午5:47写道：

**Comment by qiang333** [comment]
作者您好！
可以问一下在RAF-DB这个数据集上，对着测试集调参的话，最后论文报告结果是最好的测试结果，还是报告测试的平均结果。

**Comment by kaiwang960112** [comment]
报的最好的，不过跑几次都差不多，误差上下很小。

发自我的iPhone

**Comment by qiang333** [comment]
> 

非常谢谢您的回答！！！
