### ISSUE TITLE
在FERplus上训练准确率低

### ISSUE THREAD

**Issue by CNing715** [kaiwang960112/Self-Cure-Network#71]
作者你好，我想请教一个问题。

就是我用在ImageNet上预训练的res18得到的准确率在84%左右，用你分享的ijba_res18_naive.pth.tar得到的准确率只有79%左右，准确率反倒低很多。用两种预训练模型都达不到88%左右的准确率，这你认为会有什么原因呢？参数设置和你论文里说的一致

另外，请问你可以分享一份你所使用的FERplus的标签文件吗？我觉得可能这是一个影响因素，因为有很多图片的最大投票数相同。

期待回复，谢谢！

**Comment by kaiwang960112** [comment]
嗨，谢谢你的问题呀，可以告知下初始学习率，网络，然后啥优化器，然后bs。对于标签的问题，可以用softlabel。

**Comment by CNing715** [comment]
感谢回复！

初始学习率是0.01/0.1，网络是res18，adam优化器，bs尝试过512/256/128/64。

**Comment by kaiwang960112** [comment]
你用sgd也试试。

CNing715 ***@***.***>于2022年7月14日 周四上午9:37写道：

**Comment by CNing715** [comment]
用sgd得到的准确率会更低。请问还有其他可能因素吗？

**Comment by kaiwang960112** [comment]
图片的分辨率也可以确认下是多大？

发自我的iPhone

**Comment by CNing715** [comment]
resize到224*224是不是太大了？ferplus的图片是48*48的

**Comment by kaiwang960112** [comment]
你试试224？


CNing715 ***@***.***>于2022年7月14日 周四下午5:44写道：

**Comment by CNing715** [comment]
一直实验都是224，我的意思是 是不是要调小一点？

**Comment by CNing715** [comment]
用100*100测试了，准确率会更低

**Comment by kaiwang960112** [comment]
那你这个确实奇怪，你的预训练参数load是没问题的吧？这块你也要检查下

CNing715 ***@***.***>于2022年7月14日 周四下午8:08写道：

**Comment by CNing715** [comment]
请问正常情况下从ijba_res18_naive.pth.tar加载的参数有多少个呢？

**Comment by kaiwang960112** [comment]
多少个这个我也不记得了。你先用IMAGENET训练好的r18去load一下，那个性能也还不错。你要确保参数load对了，要不然就是随机初始化了。
CNing715 ***@***.***>于2022年7月15日 周五上午10:11写道：

**Comment by CNing715** [comment]
我再检查一下load参数，非常感谢你的耐心回复！
