### ISSUE TITLE
FERPlus数据集需要被对齐吗？

### ISSUE THREAD

**Issue by ChenNingL** [kaiwang960112/Self-Cure-Network#72]
作者你好，想请教一个问题。

我能复现在RAF-DB上的结果（使用的是RAF-DB开源的对齐之后的数据集），但一直复现不了在FERPlus上的结果。我用FERPLUS训练时使用的是原始图片，您的SCN论文里说图像是经过MTCNN对齐的。

请问我复现不了是因为图像没有被对齐吗？我看FERplus数据集的图像都是人脸，似乎不需要经过对齐吧？

希望您抽空解答一下我的疑惑，感谢！

**Comment by kaiwang960112** [comment]
建议对齐一下

ChenNingL ***@***.***>于2022年8月2日 周二下午5:48写道：

**Comment by ChenNingL** [comment]
谢谢您的回复。

我现在训练出来的结果是84.5%左右，您认为没有对齐对训练的影响很大吗？

另外，您能分享我一份对齐代码吗？

**Comment by qiang333** [comment]
> 

您好，可以分享一下处理fer2013flus的文件嘛

**Comment by kaiwang960112** [comment]
我已经没有那个数据集了，GitHub好像有，你去下载一下吧

qiang333 ***@***.***>于2022年9月13日 周二下午4:37写道：

**Comment by qiang333** [comment]
> 作者你好，想请教一个问题。
> 
> 我能复现在RAF-DB上的结果（使用的是RAF-DB开源的对齐之后的数据集），但一直复现不了在FERPlus上的结果。我用FERPLUS训练时使用的是原始图片，您的SCN论文里说图像是经过MTCNN对齐的。
> 
> 请问我复现不了是因为图像没有被对齐吗？我看FERplus数据集的图像都是人脸，似乎不需要经过对齐吧？
> 
> 希望您抽空解答一下我的疑惑，感谢！

您好，请问对齐后你的结果有提升嘛？
现在我也遇到和您一样的问题

**Comment by cotyyang** [comment]
> > 作者你好，想请教一个问题。
> > 我能复现在RAF-DB上的结果（使用的是RAF-DB开源的对齐之后的数据集），但一直复现不了在FERPlus上的结果。我用FERPLUS训练时使用的是原始图片，您的SCN论文里说图像是经过MTCNN对齐的。
> > 请问我复现不了是因为图像没有被对齐吗？我看FERplus数据集的图像都是人脸，似乎不需要经过对齐吧？
> > 希望您抽空解答一下我的疑惑，感谢！
> 
> 您好，请问对齐后你的结果有提升嘛？ 现在我也遇到和您一样的问题

您好，请问你对齐后提升吗，我这边对齐后基本没变化

**Comment by kaiwang960112** [comment]
你那个对齐好像没搞对吧？你可视化看看

cripple ***@***.***>于2023年1月3日 周二18:48写道：
