### ISSUE TITLE
关于人工噪声实验的噪声数据处理

### ISSUE THREAD

**Issue by WuQiangJP** [kaiwang960112/Self-Cure-Network#74]
感谢作者分享其研究成果. 这里我想请教一下, 关于你们的人工噪声实验中的噪声数据是通过什么规律来修改训练数据的标签的呢?还是说只是随机的方式抽取训练数据中一定百分比的样本的标签进行随机标签修改呢?

**Comment by kaiwang960112** [comment]
比如你随机选10%的样本，然后把他的label随机assign一个除了gt之外别的标签。然后定下来整个数据集的新标签，开始训练。

Q.Wu ***@***.***>于2022年8月30日 周二下午5:16写道：

**Comment by WuQiangJP** [comment]
了解了 非常感谢作者的回答.
