### ISSUE TITLE
测试结果问题

### ISSUE THREAD

**Issue by Chasellin** [kaiwang960112/Self-Cure-Network#76]
您好，在复现完您的训练代码得到模型后，我尝试写了确实的测试代码，请问我得到的这个结果是什么意思呢？
![image](https://user-images.githubusercontent.com/112814860/188826653-85df5fe0-fa30-4351-83e1-bc873e0a7a12.png)

**Comment by Chasellin** [comment]
我是不是在哪一步打少了标签

**Comment by kaiwang960112** [comment]
应该第一个是scn的weights，第二个是七个类别的score。

Chasellin ***@***.***>于2022年9月7日 周三下午4:52写道：
