### ISSUE TITLE
Upload resnet18 model pretrained on ms celeb 1m?

### ISSUE THREAD

**Issue by amirhfarzaneh** [kaiwang960112/Self-Cure-Network#9]
Hi, you have stated that you use a resnet 18 that is pretrained on ms celeb 1m. Can you please provide this model?

**Comment by kaiwang960112** [comment]
The pretrained model is same as Region Attention Network，you can load pretrained model in my RAN GitHub Repository。 Thank you for your attention on our SCN.  I am writing my thesis these days. -------- 原始邮件 --------发件人： "Amir H. Farzaneh" <notifications@github.com>日期： 2020年4月6日周一 傍晚5:29收件人： kaiwang960112/Self-Cure-Network <Self-Cure-Network@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [kaiwang960112/Self-Cure-Network] Upload resnet18 model pretrained on ms celeb 1m? (#9)
Hi, you have stated that you use a resnet 18 that is pretrained on ms celeb 1m. Can you please provide this model?

**Comment by amirhfarzaneh** [comment]
That one has the filename ijba. Isn’t it pretrained on the ijba dataset?

**Comment by kaiwang960112** [comment]
sorry. maybe the name makes misunderstanding. It just a name, the model was pretrained on ms-1m。发自我的华为手机

**Comment by kaiwang960112** [comment]
sorry. maybe the name makes misunderstanding. It just a name, the model was pretrained on ms-1m。

**Comment by amirhfarzaneh** [comment]
Ok that makes sense. Thank you and good luck with your thesis.

**Comment by kaiwang960112** [comment]
thank you. 发自我的华为手机
